# smf - SERVICE FILE

apiVersion: v1
kind: Service
metadata:
  name: service-smf
  namespace: nf-smf
spec: 
  selector:
    app: smf
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 82
      targetPort: 82