apiVersion: v1
kind: Service
metadata:
  name: service-pcrf
  namespace: nf-pcrf
spec:
  selector:
    app: pcrf
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 84
      targetPort: 84
