# SMF - DEPLOYMENT FILE

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-smf
spec:
  replicas: 1
  selector:
    matchExpressions:
      - {key: app, operator: IN, values: [smf]}
  template:
    metadata:
      labels:
        app: smf
    spec:
      containers:
        - name: smf
          image: vladutzi1/smf:latest
          ports:
            - containerPort: 82
          resources:
            limits:
              cpu: '1'
              memory: 500Mi
            requests:
              cpu: '0.5'
              memory: 250Mi