# AMF - DEPLOYMENT FILE

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-amf
spec:
  replicas: 1
  selector:
    matchExpressions:
      - {key: app, operator: IN, values: [amf]}
  template:
    metadata:
      labels:
        app: amf
    spec:
      containers:
        - name: amf
          image: vladutzi1/amf:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: '1'
              memory: 500Mi
            requests:
              cpu: '0.5'
              memory: 250Mi