# NRF - SERVICE FILE

apiVersion: v1
kind: Service
metadata:
  name: service-nrf
  namespace: nf-nrf
spec: 
  selector:
    app: nrf
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81